### ISSUE TITLE
Error when migrate

### ISSUE THREAD

**Issue by illozzam** [darbula/djangocms-custommenu#1]
When i tried to migrate my database, the followed error has appeared:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/djangocms_custommenu/models.py", line 21, in <module>
    class CustomMenu(CMSPlugin):
  File "/home/mazzolli/.virtualenvs/ticonnecte/lib/python3.6/site-packages/djangocms_custommenu/models.py", line 48, in CustomMenu
    help_text=_("Menu tree starts from this page. "
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by darbula** [comment]
Sorry for late reply. This package is still not compatible with django>=2.0 and python3.

This source of this issue is following change described in Django 2.0 [release notes](https://docs.djangoproject.com/en/2.2/releases/2.0/#features-removed-in-2-0):

> * The `on_delete` argument for `ForeignKey` and `OneToOneField` is now required in models and migrations.

**Comment by qdotme** [comment]
Submitted a pull request resolving this issue.

**Comment by darbula** [comment]
Merged. Thank you!
